Add library functionality (PubMed-lookup) possibly
PathwayCommons/pubmed-dl pull request #2
Opened 2021-01-14 20:54 UTC by Anwesh1

2021-01-14 20:57 UTC, JohnGiorgi commented
Some questions after a quick glance (will update this after I have some more time):

1. We probably don't want to commit the raw data files to the repo (e.g. pubmed_batch_20000_to_29999_abstracts.txt)
2. We should explore `pubmed-lookup` or comparable tools as discussed, and specifically, figure out how they compare to your current script in terms of time/memory etc.

2021-01-15 00:25 UTC, jvwong requested changes
By the way I have a module for using EFETCH in the semantic-search repo to retrieve title, abstract etc, it might be worth a look: https://github.com/PathwayCommons/semantic-search/blob/master/semantic_search/ncbi.py

2021-01-15 00:25 UTC, jvwong commented on requests_test.py
> +search_r = requests.post(search_url)
Ask me for an EUTILS API key. We should figure out a way to include this as a URL parameter by declaring the API key as a command-line or environmental variable.

2021-01-15 00:25 UTC, jvwong commented on requests_test.py
> +search_r = requests.post(search_url)
Why use the HTTP POST method rather than GET?

2021-01-15 17:38 UTC, Anwesh1 commented on requests_test.py
> +search_r = requests.post(search_url)
The first few lines I got from a stack overflow and when I ran it I got good data, so I didn't to mess with it too much. That's why I didn't change the HTTP POST.

2021-01-21 22:00 UTC, closed without merging